services:

  qbittorrent:
    image: linuxserver/qbittorrent:4.6.5
    container_name: qbittorrent
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - WEBUI_PORT=8080
      - WEBUI_USERNAME=admin
      - WEBUI_PASSWORD=111111
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - ./qbit-config:/config
      - /data:/data
    networks:
      - media-net


  media-bot:
    build: ./media-bot
    container_name: media-bot
    command: ["python", "-u", "runner.py"]
    restart: unless-stopped
    depends_on:
      - qbittorrent
    environment:
      - QBIT_URL=http://qbittorrent:8080
      - QBIT_USER=admin
      - QBIT_PASS=111111
    volumes:
      - ./media-bot/data:/app/data
    networks:
      - media-net


  javinizer:
    image: javinizer/javinizer:latest-cli
    container_name: javinizer
    restart: unless-stopped
    volumes:
      - /data:/data
      - /docker/media-stack/javinizer-config:/root/.local/share/javinizer
    networks:
      - media-net
    command:
      - pwsh
      - -Command
      - >
        Import-Module Javinizer;
        while ($$true) {
          Javinizer -Path '/data' -DestinationPath '/data' -Recurse;
          Start-Sleep -Seconds 300
        }


  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    ports:
      - "8096:8096"
    volumes:
      - ./jellyfin-config:/config
      - /data:/media
    networks:
      - media-net


  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - media-net


networks:
  media-net:
    driver: bridge
