services:

  qbittorrent:
    image: linuxserver/qbittorrent:4.6.5
    container_name: qbittorrent
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Ho_Chi_Minh
      - WEBUI_PORT=8080
    volumes:
      - ./qbit-config:/config
      - /data:/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      - media-net

  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    ports:
      - "8096:8096"
    environment:
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - ./jellyfin-config:/config
      - /data/movies:/media
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/dri:/dev/dri
    networks:
      - media-net

  media-bot:
    image: python:3.11-slim
    container_name: media-bot
    restart: unless-stopped
    working_dir: /app
    command: sh -c "pip install requests beautifulsoup4 && python runner.py"
    volumes:
      - ./media-bot:/app
      - ./media-bot/data:/app/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - QBIT_URL=http://qbittorrent:8080
      - QBIT_USER=admin
      - QBIT_PASS=111111
      - TZ=Asia/Ho_Chi_Minh
    depends_on:
      - qbittorrent
    networks:
      - media-net

  qbit-optimizer:
    image: python:3.11-slim
    container_name: qbit-optimizer
    restart: unless-stopped
    working_dir: /app
    command: sh -c "pip install requests && python qbit_optimizer.py"
    volumes:
      - ./media-bot:/app
      - ./media-bot/data:/app/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - QBIT_URL=http://qbittorrent:8080
      - QBIT_USER=admin
      - QBIT_PASS=111111
      - TZ=Asia/Ho_Chi_Minh
    depends_on:
      - qbittorrent
    networks:
      - media-net

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      - media-net

networks:
  media-net:
    driver: bridge

volumes:
  portainer_data:
