services:

  qbittorrent:
    image: linuxserver/qbittorrent:4.6.5
    container_name: qbittorrent
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - WEBUI_PORT=8080
      - WEBUI_USERNAME=admin
      - WEBUI_PASSWORD=111111
      - TZ=Asia/Ho_Chi_Minh
      - PUID=1000
      - PGID=1000
    volumes:
      - ./qbit-config:/config
      - /data:/data
    networks:
      - media-net

  media-bot:
    build: ./media-bot
    container_name: media-bot
    restart: unless-stopped
    command: ["python", "-u", "runner.py"]
    depends_on:
      - qbittorrent
    volumes:
      - ./media-bot/data:/app/data
      - /data:/data
    environment:
      - QBIT_URL=http://qbittorrent:8080
      - QBIT_USER=admin
      - QBIT_PASS=111111
    networks:
      - media-net

  media-bot-post:
    build: ./media-bot
    container_name: media-bot-post
    restart: unless-stopped
    command: ["python", "-u", "post_processor.py"]
    depends_on:
      - qbittorrent
      - javinizer
    volumes:
      - ./media-bot/data:/app/data
      - /data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - QBIT_URL=http://qbittorrent:8080
      - QBIT_USER=admin
      - QBIT_PASS=111111
    networks:
      - media-net

  javinizer:
    image: javinizer/javinizer:latest-cli
    container_name: javinizer
    restart: unless-stopped
    volumes:
      - /data/movies:/data
    networks:
      - media-net

  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    ports:
      - "8096:8096"
    volumes:
      - ./jellyfin-config:/config
      - /data/movies:/media
    environment:
      - TZ=Asia/Ho_Chi_Minh
    networks:
      - media-net

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer-data:/data
    networks:
      - media-net

networks:
  media-net:
    driver: bridge